/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.JOptionPane;

/**
 * AddContactPanel.java
 * @author R. Yson
 * JPANEL for entering contact details into app
 */
public class AddContactPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddContact
     */
    public AddContactPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        lblEnterContactInfo = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblContactType = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        comboContactType = new javax.swing.JComboBox();
        lblMobileNumber = new javax.swing.JLabel();
        lblHomeNumber = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        txtHomeNumber = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAddContact = new javax.swing.JButton();
        lblContactInstruction = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(null);

        lblEnterContactInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEnterContactInfo.setForeground(new java.awt.Color(204, 204, 204));
        lblEnterContactInfo.setText("Enter Contact Info");
        add(lblEnterContactInfo);
        lblEnterContactInfo.setBounds(152, 29, 222, 29);

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(204, 204, 204));
        lblFirstName.setText("First Name:");
        add(lblFirstName);
        lblFirstName.setBounds(61, 133, 79, 17);

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(204, 204, 204));
        lblLastName.setText("Last Name:");
        add(lblLastName);
        lblLastName.setBounds(61, 183, 78, 17);

        lblContactType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContactType.setForeground(new java.awt.Color(204, 204, 204));
        lblContactType.setText("Contact Type:");
        add(lblContactType);
        lblContactType.setBounds(61, 234, 98, 17);
        add(txtFirstName);
        txtFirstName.setBounds(212, 133, 227, 20);
        add(txtLastName);
        txtLastName.setBounds(212, 183, 231, 20);

        comboContactType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboContactType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Faculty" }));
        add(comboContactType);
        comboContactType.setBounds(215, 233, 228, 21);

        lblMobileNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMobileNumber.setForeground(new java.awt.Color(204, 204, 204));
        lblMobileNumber.setText("Mobile Number:");
        add(lblMobileNumber);
        lblMobileNumber.setBounds(61, 284, 109, 17);

        lblHomeNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHomeNumber.setForeground(new java.awt.Color(204, 204, 204));
        lblHomeNumber.setText("Home Number:");
        add(lblHomeNumber);
        lblHomeNumber.setBounds(61, 334, 106, 17);

        lblEmailAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmailAddress.setForeground(new java.awt.Color(204, 204, 204));
        lblEmailAddress.setText("Email Address:");
        add(lblEmailAddress);
        lblEmailAddress.setBounds(61, 384, 101, 17);
        add(txtMobileNumber);
        txtMobileNumber.setBounds(215, 284, 228, 20);
        add(txtHomeNumber);
        txtHomeNumber.setBounds(215, 334, 228, 20);
        add(txtEmailAddress);
        txtEmailAddress.setBounds(215, 384, 228, 20);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Cancel");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(61, 439, 188, 30);

        btnAddContact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddContact.setText("Add Contact");
        btnAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddContactActionPerformed(evt);
            }
        });
        add(btnAddContact);
        btnAddContact.setBounds(255, 439, 188, 30);

        lblContactInstruction.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblContactInstruction.setForeground(new java.awt.Color(204, 204, 204));
        lblContactInstruction.setText("Please enter details here:");
        add(lblContactInstruction);
        lblContactInstruction.setBounds(61, 88, 154, 15);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "CONTACT LIST");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddContactActionPerformed
        JOptionPane.showMessageDialog(null, "New contact added!", "Attention", JOptionPane.WARNING_MESSAGE);   
    }//GEN-LAST:event_btnAddContactActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddContact;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboContactType;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblContactInstruction;
    private javax.swing.JLabel lblContactType;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEnterContactInfo;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomeNumber;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHomeNumber;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNumber;
    // End of variables declaration//GEN-END:variables
}
