/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.awt.FlowLayout;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;
/**
 * AdministrationPanelUploads.java
 * @author D. Whelan
 * JPANEL for uploading files to app
 */
public class AdministrationPanelUploads extends javax.swing.JPanel {

    /**
     * Creates new form AdministrationPanelUploads
     */
    public AdministrationPanelUploads() {
        initComponents();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUploads = new javax.swing.JLabel();
        lblUploadsIntro = new javax.swing.JLabel();
        lblUploadsIntro1 = new javax.swing.JLabel();
        lblUploadsIntro2 = new javax.swing.JLabel();
        btnUploadTech = new javax.swing.JButton();
        btnUploadSci = new javax.swing.JButton();
        btnBack4 = new javax.swing.JButton();
        btnUploadMaths = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMaths = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSci = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTech = new javax.swing.JTextArea();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        lblUploads.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblUploads.setForeground(new java.awt.Color(204, 204, 204));
        lblUploads.setText("Uploads");
        add(lblUploads);
        lblUploads.setBounds(200, 20, 140, 40);

        lblUploadsIntro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUploadsIntro.setForeground(new java.awt.Color(204, 204, 204));
        lblUploadsIntro.setText("Science");
        add(lblUploadsIntro);
        lblUploadsIntro.setBounds(220, 270, 60, 17);

        lblUploadsIntro1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUploadsIntro1.setForeground(new java.awt.Color(204, 204, 204));
        lblUploadsIntro1.setText("Technology");
        add(lblUploadsIntro1);
        lblUploadsIntro1.setBounds(210, 440, 90, 17);

        lblUploadsIntro2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUploadsIntro2.setForeground(new java.awt.Color(204, 204, 204));
        lblUploadsIntro2.setText("Maths");
        add(lblUploadsIntro2);
        lblUploadsIntro2.setBounds(220, 100, 60, 17);

        btnUploadTech.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUploadTech.setText("Upload");
        btnUploadTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadTechActionPerformed(evt);
            }
        });
        add(btnUploadTech);
        btnUploadTech.setBounds(390, 530, 80, 28);

        btnUploadSci.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUploadSci.setText("Upload");
        btnUploadSci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadSciActionPerformed(evt);
            }
        });
        add(btnUploadSci);
        btnUploadSci.setBounds(390, 360, 80, 28);

        btnBack4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack4.setText("Back");
        btnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack4ActionPerformed(evt);
            }
        });
        add(btnBack4);
        btnBack4.setBounds(140, 640, 214, 28);

        btnUploadMaths.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUploadMaths.setText("Upload");
        btnUploadMaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadMathsActionPerformed(evt);
            }
        });
        add(btnUploadMaths);
        btnUploadMaths.setBounds(390, 190, 80, 28);

        txtMaths.setColumns(20);
        txtMaths.setRows(5);
        jScrollPane1.setViewportView(txtMaths);

        add(jScrollPane1);
        jScrollPane1.setBounds(120, 120, 260, 96);

        txtSci.setColumns(20);
        txtSci.setRows(5);
        jScrollPane2.setViewportView(txtSci);

        add(jScrollPane2);
        jScrollPane2.setBounds(120, 290, 260, 96);

        txtTech.setColumns(20);
        txtTech.setRows(5);
        jScrollPane3.setViewportView(txtTech);

        add(jScrollPane3);
        jScrollPane3.setBounds(120, 460, 260, 96);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

//MouseClick-SetTech   
    private void btnUploadTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadTechActionPerformed
    //Writes note to file TechLetureNotes.txt. The saved file can then be read in CourseContentNotesPanel. 
        
    /*
     *Code modified from Frances Sheridan's File IO videos
     *https://www.youtube.com/watch?v=dDsCP3dyspE
     */    
        
        String tech = txtTech.getText();
        try {
            if (txtTech.getText().isEmpty()) {
                throw new Exception("You must Entre a note first");
            }
            File outFile; //Declaring instance of File object as outFile object
            FileWriter fw; //Declaring instance of FileWriter as fw object
            BufferedWriter bw; //Declaring instance of BufferedWriter as bw object

            outFile = new File("TechLetureNotes.txt"); //Creating instance of new outFile object
            fw = new FileWriter(outFile, true); // Creating instance of new FileWriter object
            bw = new BufferedWriter(fw); // Creating instance of BufferedWriter object

            bw.write(tech); // Grubbing the text from the text field and writing it to the file
            bw.newLine(); //writing in new line

            bw.close(); //Closed the BufferedWriter
            JOptionPane.showMessageDialog(null, "Saved", "Information", JOptionPane.PLAIN_MESSAGE);
            
            txtTech.setText("");
        }
        catch (Exception e) {
            System.out.println("Error writing to file: " + e);
        }
        
    }//GEN-LAST:event_btnUploadTechActionPerformed

//MouseClick-SetSci    
    private void btnUploadSciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadSciActionPerformed
    //Writes note to file SciLetureNotes.txt. The saved file can then be read in CourseContentNotesPanel.  
        
    /*
     *Code modified from Frances Sheridan's File IO videos
     *https://www.youtube.com/watch?v=dDsCP3dyspE
     */    
        
        String sci = txtSci.getText();
        try {
            if (txtSci.getText().isEmpty()) {
                throw new Exception("You must Entre a note first");
            }
            File outFile; //Declaring instance of File object as outFile object
            FileWriter fw; //Declaring instance of FileWriter as fw object
            BufferedWriter bw; //Declaring instance of BufferedWriter as bw object

            outFile = new File("SciLetureNotes.txt"); //Creating instance of new outFile object
            fw = new FileWriter(outFile, true); // Creating instance of new FileWriter object
            bw = new BufferedWriter(fw); // Creating instance of BufferedWriter object

            bw.write(sci); // Grubbing the text from the text field and writing it to the file
            bw.newLine(); //writing in new line

            bw.close(); //Closed the BufferedWriter
            JOptionPane.showMessageDialog(null, "Saved", "Information", JOptionPane.PLAIN_MESSAGE);
            
            txtSci.setText("");
        }
        catch (Exception e) {
            System.out.println("Error writing to file: " + e);
        }
        
    }//GEN-LAST:event_btnUploadSciActionPerformed

//MouseClick-Back    
    private void btnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack4ActionPerformed
    //Navigates back to Admin 
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "ADMIN");
        }
        
    }//GEN-LAST:event_btnBack4ActionPerformed

//MouseClick-SetMaths    
    private void btnUploadMathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadMathsActionPerformed
    //Writes note to file SciLetureNotes.txt. The saved file can then be read in CourseContentNotesPanel.  
        
    /*
     *Code modified from Frances Sheridan's File IO videos
     *https://www.youtube.com/watch?v=dDsCP3dyspE
     */    
        
        String maths = txtMaths.getText();
        try {
            if (txtMaths.getText().isEmpty()) {
                throw new Exception("You must Entre a note first");
            }
            File outFile; //Declaring instance of File object as outFile object
            FileWriter fw; //Declaring instance of FileWriter as fw object
            BufferedWriter bw; //Declaring instance of BufferedWriter as bw object

            outFile = new File("MathsLetureNotes.txt"); //Creating instance of new outFile object
            fw = new FileWriter(outFile, true); // Creating instance of new FileWriter object
            bw = new BufferedWriter(fw); // Creating instance of BufferedWriter object

            bw.write(maths); // Grubbing the text from the text field and writing it to the file
            bw.newLine(); //writing in new line

            bw.close(); //Closed the BufferedWriter
            JOptionPane.showMessageDialog(null, "Saved", "Information", JOptionPane.PLAIN_MESSAGE); 
            
            txtMaths.setText("");
        }
        catch (Exception e) {
            System.out.println("Error writing to file: " + e);
        }
        
    }//GEN-LAST:event_btnUploadMathsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack4;
    private javax.swing.JButton btnUploadMaths;
    private javax.swing.JButton btnUploadSci;
    private javax.swing.JButton btnUploadTech;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblUploads;
    private javax.swing.JLabel lblUploadsIntro;
    private javax.swing.JLabel lblUploadsIntro1;
    private javax.swing.JLabel lblUploadsIntro2;
    private javax.swing.JTextArea txtMaths;
    private javax.swing.JTextArea txtSci;
    private javax.swing.JTextArea txtTech;
    // End of variables declaration//GEN-END:variables
}
