/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 * CalendarPanel.java
 * @author R. Yson
 * JPANEL for viewing calendars recording school timetable and other events
 */
public class CalendarPanel extends javax.swing.JPanel {

    /**
     * Creates new form CalendarMainScreenPanel
     */
    public CalendarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCalendar = new javax.swing.JLabel();
        scrollNextCalendar = new javax.swing.JScrollPane();
        tableThisCalendar = new javax.swing.JTable();
        lblNextWeek = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblThisWeek = new javax.swing.JLabel();
        scrollThisCalendar = new javax.swing.JScrollPane();
        tableNextCalendar = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(null);

        lblCalendar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCalendar.setForeground(new java.awt.Color(204, 204, 204));
        lblCalendar.setText("Calendar");
        add(lblCalendar);
        lblCalendar.setBounds(194, 29, 105, 29);

        tableThisCalendar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0900", null, null, null, null, null, null, ""},
                {"1000", null, null, null, null, null, null, ""},
                {"1100", null, null, null, null, null, null, ""},
                {"1200", null, null, null, null, null, null, ""},
                {"1300", null, null, null, null, null, null, ""},
                {"1400", null, null, null, null, null, null, ""},
                {"1500", null, null, null, null, null, null, ""},
                {"1600", null, null, null, null, null, null, ""}
            },
            new String [] {
                "TIME", "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableThisCalendar.setColumnSelectionAllowed(true);
        tableThisCalendar.getTableHeader().setReorderingAllowed(false);
        scrollNextCalendar.setViewportView(tableThisCalendar);
        tableThisCalendar.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        add(scrollNextCalendar);
        scrollNextCalendar.setBounds(42, 316, 420, 155);

        lblNextWeek.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNextWeek.setForeground(new java.awt.Color(204, 204, 204));
        lblNextWeek.setText("Your schedule for NEXT week:");
        add(lblNextWeek);
        lblNextWeek.setBounds(42, 290, 181, 15);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(138, 554, 214, 30);

        lblThisWeek.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThisWeek.setForeground(new java.awt.Color(204, 204, 204));
        lblThisWeek.setText("Your schedule for THIS week:");
        add(lblThisWeek);
        lblThisWeek.setBounds(42, 89, 206, 17);

        tableNextCalendar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0900", null, null, null, null, null, null, null},
                {"1000", null, null, null, null, null, null, null},
                {"1100", null, null, null, null, null, null, null},
                {"1200", null, null, null, null, null, null, null},
                {"1300", null, null, null, null, null, null, null},
                {"1400", null, null, null, null, null, null, null},
                {"1500", null, null, null, null, null, null, null},
                {"1600", null, null, null, null, null, null, null}
            },
            new String [] {
                "TIME", "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNextCalendar.setColumnSelectionAllowed(true);
        tableNextCalendar.getTableHeader().setReorderingAllowed(false);
        scrollThisCalendar.setViewportView(tableNextCalendar);
        tableNextCalendar.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tableNextCalendar.getColumnModel().getColumnCount() > 0) {
            tableNextCalendar.getColumnModel().getColumn(7).setResizable(false);
        }

        add(scrollThisCalendar);
        scrollThisCalendar.setBounds(42, 117, 420, 155);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "STUDENT");
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCalendar;
    private javax.swing.JLabel lblNextWeek;
    private javax.swing.JLabel lblThisWeek;
    private javax.swing.JScrollPane scrollNextCalendar;
    private javax.swing.JScrollPane scrollThisCalendar;
    private javax.swing.JTable tableNextCalendar;
    private javax.swing.JTable tableThisCalendar;
    // End of variables declaration//GEN-END:variables
}
