/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 * CommunicationsPanel.java
 * @author R. Yson
 * JPANEL for viewing "Communications" navigation page
 */
public class CommunicationsPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunicationsMainScreenPanel
     */
    public CommunicationsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCommunications = new javax.swing.JLabel();
        btnImportantNews = new javax.swing.JButton();
        btnContactList = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(null);

        lblCommunications.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCommunications.setForeground(new java.awt.Color(204, 204, 204));
        lblCommunications.setText("Communications");
        add(lblCommunications);
        lblCommunications.setBounds(170, 30, 210, 29);

        btnImportantNews.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImportantNews.setText("Important News");
        btnImportantNews.setPreferredSize(new java.awt.Dimension(145, 25));
        btnImportantNews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportantNewsActionPerformed(evt);
            }
        });
        add(btnImportantNews);
        btnImportantNews.setBounds(150, 130, 228, 65);

        btnContactList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnContactList.setText("Contact List");
        btnContactList.setPreferredSize(new java.awt.Dimension(145, 25));
        btnContactList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactListActionPerformed(evt);
            }
        });
        add(btnContactList);
        btnContactList.setBounds(150, 240, 228, 65);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.setPreferredSize(new java.awt.Dimension(145, 25));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(150, 340, 228, 65);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(500, 700));
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "STUDENT");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnContactListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactListActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "CONTACT LIST");
        }
    }//GEN-LAST:event_btnContactListActionPerformed

    private void btnImportantNewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportantNewsActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "NEWS");
        }
    }//GEN-LAST:event_btnImportantNewsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContactList;
    private javax.swing.JButton btnImportantNews;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCommunications;
    // End of variables declaration//GEN-END:variables
}
