/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.JOptionPane;

/**
 * ContactListPanel.java
 * @author R. Yson
 * JPANEL for viewing contacts stored on application
 */
public class ContactListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContactList
     */
    public ContactListPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContactList = new javax.swing.JLabel();
        comboContactList = new javax.swing.JComboBox();
        lblShowDetails = new javax.swing.JLabel();
        btnAddContact = new javax.swing.JButton();
        btnDeleteContact = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(null);

        lblContactList.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblContactList.setForeground(new java.awt.Color(204, 204, 204));
        lblContactList.setText("Contact List");
        add(lblContactList);
        lblContactList.setBounds(179, 29, 143, 29);

        comboContactList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboContactList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alabi Habeeb", "King Patrick", "Whelan Don", "Yson Rachelle" }));
        add(comboContactList);
        comboContactList.setBounds(85, 88, 335, 30);

        lblShowDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblShowDetails.setText("<details for contact selected appear here>");
        add(lblShowDetails);
        lblShowDetails.setBounds(85, 230, 327, 317);

        btnAddContact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddContact.setText("Add New Contact");
        btnAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddContactActionPerformed(evt);
            }
        });
        add(btnAddContact);
        btnAddContact.setBounds(85, 158, 131, 30);

        btnDeleteContact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteContact.setText("Delete Contact");
        btnDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteContactActionPerformed(evt);
            }
        });
        add(btnDeleteContact);
        btnDeleteContact.setBounds(286, 158, 126, 30);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(143, 565, 214, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "COMMUNICATIONS");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddContactActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "ADD CONTACT");   
        }
    }//GEN-LAST:event_btnAddContactActionPerformed

    private void btnDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteContactActionPerformed
        JOptionPane.showMessageDialog(null, "Contact deleted!", "Attention", JOptionPane.WARNING_MESSAGE);   
    }//GEN-LAST:event_btnDeleteContactActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddContact;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteContact;
    private javax.swing.JComboBox comboContactList;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblContactList;
    private javax.swing.JLabel lblShowDetails;
    // End of variables declaration//GEN-END:variables
}
