/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import ie.SchoolManagmentSystem.Science;
import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.JOptionPane;

/**
 * CourseContentSciencePanel.java
 * @author H. Alabi & R. Yson
 * JPANEL for Science quiz resource
 */
public class CourseContentSciencePanel extends javax.swing.JPanel {

    /**
     * Creates new form Science
     */
     Science sci[];
     int Count = 0;
    
    public CourseContentSciencePanel() {
        initComponents();
        
      sci = new Science[100];
      Count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bground = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LblBrain1 = new javax.swing.JLabel();
        lblScienceQ1 = new javax.swing.JLabel();
        txtAnw1 = new javax.swing.JTextField();
        txtAnw2 = new javax.swing.JTextField();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        txtAnw3 = new javax.swing.JTextField();
        lblC = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        txtAnw4 = new javax.swing.JTextField();
        txtAnw5 = new javax.swing.JTextField();
        lblE = new javax.swing.JLabel();
        txtAnw6 = new javax.swing.JTextField();
        lblG = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        txtAnw7 = new javax.swing.JTextField();
        txtAnw8 = new javax.swing.JTextField();
        lblH = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        txtAnw9 = new javax.swing.JTextField();
        txtAnw10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        btnDis = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblJ = new javax.swing.JLabel();
        btnNext1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(null);

        bground.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bground.setForeground(new java.awt.Color(204, 204, 204));
        bground.setText("Science");
        add(bground);
        bground.setBounds(199, 29, 110, 29);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(70, 660, 360, 30);
        add(jLabel2);
        jLabel2.setBounds(412, 69, 0, 0);
        add(LblBrain1);
        LblBrain1.setBounds(36, 60, 0, 0);

        lblScienceQ1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblScienceQ1.setForeground(new java.awt.Color(204, 204, 204));
        lblScienceQ1.setText("1.) Identify the correct areas of the plant cell:");
        add(lblScienceQ1);
        lblScienceQ1.setBounds(80, 70, 351, 17);
        add(txtAnw1);
        txtAnw1.setBounds(70, 510, 156, 20);
        add(txtAnw2);
        txtAnw2.setBounds(70, 540, 156, 20);

        lblA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblA.setForeground(new java.awt.Color(204, 204, 204));
        lblA.setText("A");
        add(lblA);
        lblA.setBounds(50, 510, 11, 22);

        lblB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblB.setForeground(new java.awt.Color(204, 204, 204));
        lblB.setText("B");
        add(lblB);
        lblB.setBounds(50, 540, 11, 22);
        add(txtAnw3);
        txtAnw3.setBounds(70, 570, 156, 20);

        lblC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblC.setForeground(new java.awt.Color(204, 204, 204));
        lblC.setText("C");
        add(lblC);
        lblC.setBounds(50, 570, 11, 22);

        lblD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblD.setForeground(new java.awt.Color(204, 204, 204));
        lblD.setText("D");
        add(lblD);
        lblD.setBounds(50, 600, 12, 22);
        add(txtAnw4);
        txtAnw4.setBounds(70, 600, 155, 20);
        add(txtAnw5);
        txtAnw5.setBounds(70, 630, 155, 20);

        lblE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblE.setForeground(new java.awt.Color(204, 204, 204));
        lblE.setText("E");
        add(lblE);
        lblE.setBounds(50, 630, 10, 22);
        add(txtAnw6);
        txtAnw6.setBounds(270, 510, 156, 20);

        lblG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblG.setForeground(new java.awt.Color(204, 204, 204));
        lblG.setText("G");
        add(lblG);
        lblG.setBounds(240, 540, 12, 22);

        lblF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblF.setForeground(new java.awt.Color(204, 204, 204));
        lblF.setText("F");
        add(lblF);
        lblF.setBounds(240, 510, 9, 22);
        add(txtAnw7);
        txtAnw7.setBounds(270, 540, 156, 20);
        add(txtAnw8);
        txtAnw8.setBounds(270, 570, 156, 20);

        lblH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblH.setForeground(new java.awt.Color(204, 204, 204));
        lblH.setText("H");
        add(lblH);
        lblH.setBounds(240, 570, 12, 22);

        lblI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblI.setForeground(new java.awt.Color(204, 204, 204));
        lblI.setText("I");
        add(lblI);
        lblI.setBounds(240, 600, 7, 22);
        add(txtAnw9);
        txtAnw9.setBounds(270, 600, 156, 20);
        add(txtAnw10);
        txtAnw10.setBounds(270, 630, 156, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("J");
        add(jLabel12);
        jLabel12.setBounds(240, 630, 8, 22);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/plant cell 2.jpg"))); // NOI18N
        add(lblImage);
        lblImage.setBounds(70, 90, 360, 380);

        btnDis.setText("Display");
        btnDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisActionPerformed(evt);
            }
        });
        add(btnDis);
        btnDis.setBounds(210, 480, 80, 23);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(320, 480, 80, 23);

        btnDelete.setText("Remove");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(100, 480, 80, 23);

        lblJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        add(lblJ);
        lblJ.setBounds(0, 0, 500, 740);

        btnNext1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNext1.setText("Next");
        btnNext1.setPreferredSize(new java.awt.Dimension(188, 30));
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        add(btnNext1);
        btnNext1.setBounds(273, 655, 156, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SUBJECTS");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String anw1, anw2, anw3, anw4, anw5, anw6, anw7, anw8,anw9, anw10;
        Science s;
    
        anw1 = txtAnw1.getText();
        anw2 = txtAnw2.getText();
        anw3 = txtAnw3.getText();
        anw4 = txtAnw4.getText();
        anw5 = txtAnw5.getText();
        anw6 = txtAnw6.getText();
        anw7 = txtAnw7.getText();
        anw8 = txtAnw8.getText();
        anw9 = txtAnw9.getText();
        anw10 = txtAnw10.getText();
        

  
     
        s = new Science (anw1, anw2, anw3,anw4, anw5, anw6, anw7, anw8, anw9, anw10);

        JOptionPane.showMessageDialog(null, "Successfully added Answers.", "Congratulations", JOptionPane.PLAIN_MESSAGE);
        
        sci[Count] = s;
        Count++; 
     
        txtAnw1.setText("");
        txtAnw2.setText("");
        txtAnw3.setText("");
        txtAnw4.setText("");
        txtAnw5.setText("");
        txtAnw6.setText("");
        txtAnw7.setText("");
        txtAnw8.setText("");
        txtAnw9.setText("");
        txtAnw10.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisActionPerformed
       String anw1, anw2 ,anw3,anw4, anw5, anw6, anw7, anw8, anw9, anw10;
        Science s;   
        
        if(Count == 0){  
            JOptionPane.showMessageDialog(null, "Ther are no answers saved.", "Attention!", JOptionPane.WARNING_MESSAGE);
             txtAnw1.setText("");
             txtAnw2.setText("");
             txtAnw3.setText("");
             txtAnw4.setText("");
             txtAnw5.setText("");
             txtAnw6.setText("");
             txtAnw7.setText("");
             txtAnw8.setText("");
             txtAnw9.setText("");
             txtAnw10.setText("");
        }  
       
        for (int i=0; i < Count; i++){   
            s = sci[i];
            anw1 = s.getAnw1();
            anw2 = s.getAnw2();
            anw3 = s.getAnw3();
            anw4 = s.getAnw4();
            anw5 = s.getAnw5();
            anw6 = s.getAnw6();
            anw7 = s.getAnw7();
            anw8 = s.getAnw8();
            anw9 = s.getAnw9();
            anw10 = s.getAnw10();
            
       
            JOptionPane.showMessageDialog(null, "Answer one " + anw1 + "\n" + "Answer two :" + anw2 + "\n" + "Answer three :" + anw3 + "\n" + "Answer four :" + anw4 + "\n" + "Answer five :" + anw5 + "\n" + "Answer six :" + anw6 + "\n"+ "Answer seven :" + anw7 + "\n" + "Answer eight :" + anw8 + "\n" + "Answer nine :" + anw9 + "\n" + "Answer ten :" + anw10,"Attention!", JOptionPane.PLAIN_MESSAGE);            
            
             txtAnw1.setText("");
             txtAnw2.setText("");
             txtAnw3.setText("");
             txtAnw4.setText("");
             txtAnw5.setText("");
             txtAnw6.setText("");
             txtAnw7.setText("");
             txtAnw8.setText("");
             txtAnw9.setText("");
             txtAnw10.setText("");
             
        }
        
            
             
        
    }//GEN-LAST:event_btnDisActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
          String anw1, anw2, anw3,anw4, anw5, anw6, anw7, anw8, anw9, anw10;
        Science s; 
        
        anw1 = txtAnw1.getText();
        anw2 = txtAnw2.getText();
        anw3 = txtAnw3.getText();
        anw4 = txtAnw4.getText();
        anw5 = txtAnw5.getText();
        anw6 = txtAnw6.getText();
        anw7 = txtAnw7.getText();
        anw8 = txtAnw8.getText();
        anw9 = txtAnw9.getText();
        anw10 = txtAnw10.getText();
        
        for (int i=0; i < Count; i++){ 
                s = sci[i];
                if (anw1.equals(s.getAnw1()) && anw2.equals(s.getAnw2()) && anw3.equals(s.getAnw3()) && anw4.equals(s.getAnw4()) && anw5.equals(s.getAnw5()) && anw6.equals(s.getAnw6()) && anw7.equals(s.getAnw7()) && anw8.equals(s.getAnw8()) && anw9.equals(s.getAnw9()) && anw10.equals(s.getAnw10())){                 
                    sci[i] = sci[Count-1];
                    sci[Count-1] = null;
                    Count--;           
                }  
                JOptionPane.showMessageDialog(null, "Submissions deleted.", "Attention!", JOptionPane.WARNING_MESSAGE);
            

            txtAnw1.setText("");
            txtAnw2.setText("");
            txtAnw3.setText("");
            txtAnw4.setText("");
            txtAnw5.setText("");
            txtAnw6.setText("");
            txtAnw7.setText("");
            txtAnw8.setText("");
            txtAnw9.setText("");
            txtAnw10.setText("");
            return;
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed
          

        
         


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblBrain1;
    private javax.swing.JLabel bground;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDis;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblE;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblH;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblJ;
    private javax.swing.JLabel lblScienceQ1;
    private javax.swing.JTextField txtAnw1;
    private javax.swing.JTextField txtAnw10;
    private javax.swing.JTextField txtAnw2;
    private javax.swing.JTextField txtAnw3;
    private javax.swing.JTextField txtAnw4;
    private javax.swing.JTextField txtAnw5;
    private javax.swing.JTextField txtAnw6;
    private javax.swing.JTextField txtAnw7;
    private javax.swing.JTextField txtAnw8;
    private javax.swing.JTextField txtAnw9;
    // End of variables declaration//GEN-END:variables
}
