/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * CourseContentNotesPanel.java
 * @author H. Alabi / D. Whelan
 * JPANEL for uploading lecture notes
 */
public class CourseContentNotesPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotesPanel
     */
    public CourseContentNotesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLectureNotes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTech = new javax.swing.JTextArea();
        btnGetSci = new javax.swing.JButton();
        lblLectureNotesInstruction = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblLectureNotesInstruction2 = new javax.swing.JLabel();
        lblLectureNotesInstruction3 = new javax.swing.JLabel();
        btnGetTech = new javax.swing.JButton();
        btnGetMaths = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMaths = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSci = new javax.swing.JTextArea();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        lblLectureNotes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLectureNotes.setForeground(new java.awt.Color(204, 204, 204));
        lblLectureNotes.setText("Lecture Notes");
        add(lblLectureNotes);
        lblLectureNotes.setBounds(164, 29, 167, 29);

        txtTech.setColumns(20);
        txtTech.setRows(5);
        jScrollPane1.setViewportView(txtTech);

        add(jScrollPane1);
        jScrollPane1.setBounds(140, 450, 220, 130);

        btnGetSci.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGetSci.setText("Get");
        btnGetSci.setPreferredSize(new java.awt.Dimension(75, 30));
        btnGetSci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetSciActionPerformed(evt);
            }
        });
        add(btnGetSci);
        btnGetSci.setBounds(380, 370, 60, 30);

        lblLectureNotesInstruction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLectureNotesInstruction.setForeground(new java.awt.Color(204, 204, 204));
        lblLectureNotesInstruction.setText("Science");
        add(lblLectureNotesInstruction);
        lblLectureNotesInstruction.setBounds(230, 250, 60, 17);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(75, 30));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(140, 650, 214, 30);

        lblLectureNotesInstruction2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLectureNotesInstruction2.setForeground(new java.awt.Color(204, 204, 204));
        lblLectureNotesInstruction2.setText("Tech");
        add(lblLectureNotesInstruction2);
        lblLectureNotesInstruction2.setBounds(240, 430, 60, 17);

        lblLectureNotesInstruction3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLectureNotesInstruction3.setForeground(new java.awt.Color(204, 204, 204));
        lblLectureNotesInstruction3.setText("Maths");
        add(lblLectureNotesInstruction3);
        lblLectureNotesInstruction3.setBounds(230, 70, 60, 17);

        btnGetTech.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGetTech.setText("Get");
        btnGetTech.setPreferredSize(new java.awt.Dimension(75, 30));
        btnGetTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTechActionPerformed(evt);
            }
        });
        add(btnGetTech);
        btnGetTech.setBounds(380, 550, 60, 30);

        btnGetMaths.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGetMaths.setText("Get");
        btnGetMaths.setPreferredSize(new java.awt.Dimension(75, 30));
        btnGetMaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetMathsActionPerformed(evt);
            }
        });
        add(btnGetMaths);
        btnGetMaths.setBounds(380, 190, 60, 30);

        txtMaths.setColumns(20);
        txtMaths.setRows(5);
        jScrollPane2.setViewportView(txtMaths);

        add(jScrollPane2);
        jScrollPane2.setBounds(140, 90, 220, 130);

        txtSci.setColumns(20);
        txtSci.setRows(5);
        jScrollPane4.setViewportView(txtSci);

        add(jScrollPane4);
        jScrollPane4.setBounds(140, 270, 220, 130);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(500, 700));
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

//MouseClick-GetSciance 
    private void btnGetSciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetSciActionPerformed
    //Reads information from file SciLetureNotes.txt and sets it to the text area. This information was written to disc from AdministrationPanelUploads.
        
    /*
     *Code modified from Frances Sheridan's File IO video
     *https://www.youtube.com/watch?v=dDsCP3dyspE
     */    
        
        String sci;
        try {
            File inFile;//Declaring instance of File object as inFile object
            FileReader fr;//Declaring instance of FileReader as fr object
            BufferedReader br;//Declaring instance of BufferedReader as br object

            inFile = new File("SciLetureNotes.txt");//Creating instance of new inFile object
            fr = new FileReader(inFile); // Creating instance of new FileReader object
            br = new BufferedReader(fr);// Creating instance of BufferedReader object
            sci = br.readLine();

            while (sci != null) {
                txtSci.setText("");
                txtSci.setText(sci);
                sci = br.readLine(); //Will read all lines
                JOptionPane.showMessageDialog(null, "Next note", "Information", JOptionPane.PLAIN_MESSAGE);
            }
            txtTech.setText("");
            br.close();
        }
        catch (IOException ex) {
            System.out.println("Error reading to file: " + ex);
        }
        
    }//GEN-LAST:event_btnGetSciActionPerformed

//MouseClick-Back 
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "COURSE CONTENT");
        }
        
    }//GEN-LAST:event_btnBackActionPerformed

//MouseClick-GetTech
    private void btnGetTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTechActionPerformed
    //Reads information from file TechLetureNotes.txt and sets it to the text area. This information was written to disc from AdministrationPanelUploads.
        
    /*
     *Code modified from Frances Sheridan's File IO video
     *https://www.youtube.com/watch?v=dDsCP3dyspE
     */  
        
       String tech; 
       try {
            File inFile;//Declaring instance of File object as inFile object
            FileReader fr;//Declaring instance of FileReader as fr object
            BufferedReader br;//Declaring instance of BufferedReader as br object

            inFile = new File("TechLetureNotes.txt");//Creating instance of new inFile object
            fr = new FileReader(inFile); // Creating instance of new FileReader object
            br = new BufferedReader(fr);// Creating instance of BufferedReader object
            tech = br.readLine();
            
            while (tech != null) {
                txtTech.setText("");
                txtTech.setText(tech);
                tech = br.readLine(); //Will read all lines
                JOptionPane.showMessageDialog(null, "Next note", "Information", JOptionPane.PLAIN_MESSAGE);
               
            }
            txtTech.setText("");
            br.close();
        }
        catch (IOException ex) {
            System.out.println("Error reading to file: " + ex);
        }

    }//GEN-LAST:event_btnGetTechActionPerformed

//MouseClick-GetMaths
    private void btnGetMathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetMathsActionPerformed
    //Reads information from file MathsLetureNotes.txt and sets it to the text area. This information was written to disc from AdministrationPanelUploads.
        
    /*
     *Code modified from Frances Sheridan's File IO video
     *https://www.youtube.com/watch?v=dDsCP3dyspE
     */ 
        
        String maths;
        try {
            File inFile;//Declaring instance of File object as inFile object
            FileReader fr;//Declaring instance of FileReader as fr object
            BufferedReader br;//Declaring instance of BufferedReader as br object

            inFile = new File("MathsLetureNotes.txt");//Creating instance of new inFile object
            fr = new FileReader(inFile); // Creating instance of new FileReader object
            br = new BufferedReader(fr);// Creating instance of BufferedReader object
            maths = br.readLine();

            while (maths != null) {
                txtMaths.setText("");
                txtMaths.setText(maths);
                maths = br.readLine();
                JOptionPane.showMessageDialog(null, "Next note", "Information", JOptionPane.PLAIN_MESSAGE);
            }
            txtTech.setText("");
            br.close();
        }
        catch (IOException ex) {
            System.out.println("Error reading to file: " + ex);
        }
        
    }//GEN-LAST:event_btnGetMathsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGetMaths;
    private javax.swing.JButton btnGetSci;
    private javax.swing.JButton btnGetTech;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLectureNotes;
    private javax.swing.JLabel lblLectureNotesInstruction;
    private javax.swing.JLabel lblLectureNotesInstruction2;
    private javax.swing.JLabel lblLectureNotesInstruction3;
    private javax.swing.JTextArea txtMaths;
    private javax.swing.JTextArea txtSci;
    private javax.swing.JTextArea txtTech;
    // End of variables declaration//GEN-END:variables
}
