/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.JOptionPane;

/**
 * CourseContentTechnologyPanel.java
 * @author H. Alabi & R. Yson
 * JPANEL for Technology quiz resource
 */
public class CourseContentTechnologyPanel extends javax.swing.JPanel {

    /**
     * Creates new form Technology
     */
    public CourseContentTechnologyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupQuestion = new javax.swing.ButtonGroup();
        lblTechnology = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblTechQ1 = new javax.swing.JLabel();
        scrollTechnology = new javax.swing.JScrollPane();
        txtTechQ2 = new javax.swing.JTextArea();
        btnNext = new javax.swing.JButton();
        btnRBillGates = new javax.swing.JRadioButton();
        btnRProgrammer = new javax.swing.JRadioButton();
        btnRUSGovernment = new javax.swing.JRadioButton();
        btnRUnknown = new javax.swing.JRadioButton();
        lblTechQ2 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(null);

        lblTechnology.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTechnology.setForeground(new java.awt.Color(204, 204, 204));
        lblTechnology.setText("Technology");
        add(lblTechnology);
        lblTechnology.setBounds(165, 30, 148, 29);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(188, 30));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(54, 414, 180, 30);

        lblTechQ1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTechQ1.setForeground(new java.awt.Color(204, 204, 204));
        lblTechQ1.setText("1.) Who invented the Internet?");
        add(lblTechQ1);
        lblTechQ1.setBounds(54, 80, 404, 17);

        txtTechQ2.setColumns(20);
        txtTechQ2.setRows(5);
        scrollTechnology.setViewportView(txtTechQ2);

        add(scrollTechnology);
        scrollTechnology.setBounds(54, 272, 376, 96);

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNext.setText("Next");
        btnNext.setPreferredSize(new java.awt.Dimension(188, 30));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext);
        btnNext.setBounds(252, 414, 180, 30);

        btnGroupQuestion.add(btnRBillGates);
        btnRBillGates.setForeground(new java.awt.Color(204, 204, 204));
        btnRBillGates.setText("Bill Gates");
        add(btnRBillGates);
        btnRBillGates.setBounds(54, 115, 100, 23);

        btnGroupQuestion.add(btnRProgrammer);
        btnRProgrammer.setForeground(new java.awt.Color(204, 204, 204));
        btnRProgrammer.setText("A programmer");
        add(btnRProgrammer);
        btnRProgrammer.setBounds(54, 165, 120, 23);

        btnGroupQuestion.add(btnRUSGovernment);
        btnRUSGovernment.setForeground(new java.awt.Color(204, 204, 204));
        btnRUSGovernment.setText("US Government");
        add(btnRUSGovernment);
        btnRUSGovernment.setBounds(254, 115, 130, 23);

        btnGroupQuestion.add(btnRUnknown);
        btnRUnknown.setForeground(new java.awt.Color(204, 204, 204));
        btnRUnknown.setText("Unknown");
        add(btnRUnknown);
        btnRUnknown.setBounds(254, 165, 100, 23);

        lblTechQ2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTechQ2.setForeground(new java.awt.Color(204, 204, 204));
        lblTechQ2.setText("2.) Explain what an operating system is:");
        add(lblTechQ2);
        lblTechQ2.setBounds(54, 237, 275, 17);

        lblBackground.setForeground(new java.awt.Color(204, 204, 204));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SUBJECTS");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        JOptionPane.showMessageDialog(null, "Answer submitted!", "Attention", JOptionPane.WARNING_MESSAGE);  
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup btnGroupQuestion;
    private javax.swing.JButton btnNext;
    private javax.swing.JRadioButton btnRBillGates;
    private javax.swing.JRadioButton btnRProgrammer;
    private javax.swing.JRadioButton btnRUSGovernment;
    private javax.swing.JRadioButton btnRUnknown;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTechQ1;
    private javax.swing.JLabel lblTechQ2;
    private javax.swing.JLabel lblTechnology;
    private javax.swing.JScrollPane scrollTechnology;
    private javax.swing.JTextArea txtTechQ2;
    // End of variables declaration//GEN-END:variables
}
