/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.JOptionPane;

/**
 * CourseContentMenuPanel.java
 * @author H. Alabi
 * JPANEL for viewing "Course Content" navigation page
 */
public class CourseContentMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainScreenPanel
     */
    public CourseContentMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourseContent = new javax.swing.JLabel();
        btnSubjects = new javax.swing.JButton();
        btnCA = new javax.swing.JButton();
        btnNotes = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        lblCourseContent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCourseContent.setForeground(new java.awt.Color(204, 204, 204));
        lblCourseContent.setText("Course Content");
        add(lblCourseContent);
        lblCourseContent.setBounds(160, 20, 200, 29);

        btnSubjects.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubjects.setText("Subjects");
        btnSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectsActionPerformed(evt);
            }
        });
        add(btnSubjects);
        btnSubjects.setBounds(140, 90, 228, 65);

        btnCA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCA.setText("CA's");
        btnCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAActionPerformed(evt);
            }
        });
        add(btnCA);
        btnCA.setBounds(140, 200, 228, 65);

        btnNotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNotes.setText("Notes");
        btnNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotesActionPerformed(evt);
            }
        });
        add(btnNotes);
        btnNotes.setBounds(140, 310, 228, 65);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(140, 420, 228, 65);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(500, 700));
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectsActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SUBJECTS");
        }
    }//GEN-LAST:event_btnSubjectsActionPerformed

    private void btnCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "CA");
        }
    }//GEN-LAST:event_btnCAActionPerformed

    private void btnNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotesActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "NOTES");
        }
    }//GEN-LAST:event_btnNotesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "MAIN");
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCA;
    private javax.swing.JButton btnNotes;
    private javax.swing.JButton btnSubjects;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCourseContent;
    // End of variables declaration//GEN-END:variables
}
