/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import ie.SchoolManagmentSystem.Maths;
import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.JOptionPane;
/**
 * CourseContentMathsPanel.java
 * @author H. Alabi & R. Yson
 * JPANEL for maths quiz resource
 */
public class CourseContentMathsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Maths
     */
    
     Maths mat[];
     int Count = 0;
    
    public CourseContentMathsPanel() {
        initComponents();
        
     mat = new Maths[100];
      Count = 0; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMaths = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblMathsQ1 = new javax.swing.JLabel();
        lblMathsEquation1 = new javax.swing.JLabel();
        lblMathsQ1Instruction = new javax.swing.JLabel();
        lblMathsQ2 = new javax.swing.JLabel();
        lblMathsEquation2 = new javax.swing.JLabel();
        lblMathsQ2Instruction = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        txtAns1 = new javax.swing.JTextField();
        txtAns2 = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(null);

        lblMaths.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMaths.setForeground(new java.awt.Color(204, 204, 204));
        lblMaths.setText("Maths");
        add(lblMaths);
        lblMaths.setBounds(210, 20, 80, 40);

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setPreferredSize(new java.awt.Dimension(188, 30));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove);
        btnRemove.setBounds(40, 580, 100, 30);

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setText("save");
        btnSave.setPreferredSize(new java.awt.Dimension(188, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(260, 630, 180, 30);

        lblMathsQ1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMathsQ1.setForeground(new java.awt.Color(204, 204, 204));
        lblMathsQ1.setText("1. ) Solve this quadratic equation:");
        add(lblMathsQ1);
        lblMathsQ1.setBounds(61, 87, 232, 17);

        lblMathsEquation1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMathsEquation1.setForeground(new java.awt.Color(204, 204, 204));
        lblMathsEquation1.setText("ax² + bx + c = 7");
        add(lblMathsEquation1);
        lblMathsEquation1.setBounds(183, 122, 152, 22);

        lblMathsQ1Instruction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMathsQ1Instruction.setForeground(new java.awt.Color(204, 204, 204));
        lblMathsQ1Instruction.setText("Show your working below:");
        add(lblMathsQ1Instruction);
        lblMathsQ1Instruction.setBounds(61, 162, 185, 17);

        lblMathsQ2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMathsQ2.setForeground(new java.awt.Color(204, 204, 204));
        lblMathsQ2.setText("2.) Solve this quadratic equation:");
        add(lblMathsQ2);
        lblMathsQ2.setBounds(61, 340, 228, 17);

        lblMathsEquation2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMathsEquation2.setForeground(new java.awt.Color(204, 204, 204));
        lblMathsEquation2.setText("ax² + bx + c = 7");
        add(lblMathsEquation2);
        lblMathsEquation2.setBounds(183, 375, 139, 22);

        lblMathsQ2Instruction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMathsQ2Instruction.setForeground(new java.awt.Color(204, 204, 204));
        lblMathsQ2Instruction.setText("Show your working below:");
        add(lblMathsQ2Instruction);
        lblMathsQ2Instruction.setBounds(61, 415, 185, 17);

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(188, 30));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(200, 580, 110, 30);

        btnDisplay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDisplay.setText("Display");
        btnDisplay.setPreferredSize(new java.awt.Dimension(188, 30));
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        add(btnDisplay);
        btnDisplay.setBounds(370, 580, 100, 30);

        btnBack3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack3.setText("Back");
        btnBack3.setPreferredSize(new java.awt.Dimension(188, 30));
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        add(btnBack3);
        btnBack3.setBounds(60, 630, 180, 30);
        add(txtAns1);
        txtAns1.setBounds(89, 220, 320, 20);

        txtAns2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAns2ActionPerformed(evt);
            }
        });
        add(txtAns2);
        txtAns2.setBounds(70, 480, 330, 20);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(500, 700));
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents
    //This is the MouseClick-RemoveAction 
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
       
        String ans1, ans2;
        Maths m;
    
        ans1 = txtAns1.getText();
        ans2 = txtAns2.getText();

       
         for (int i = 0; i < Count; i++) {
           m = mat[i];
          if (ans1.equals(m.getAns1()) && ans2.equals(m.getAns2())) {
             mat[i] = mat[Count - 1];
             mat[Count - 1] = null;
               Count--;
             
             
                }
            }
         JOptionPane.showMessageDialog(null, "deleted.", "Gone", JOptionPane.PLAIN_MESSAGE);
             
        
    }//GEN-LAST:event_btnRemoveActionPerformed
         //This is the MouseClick-SaveAction    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
  
        String ans1, ans2;
        Maths m;
    
        ans1 = txtAns1.getText();
        ans2 = txtAns2.getText();
  
     
        m = new Maths (ans1, ans2);

        JOptionPane.showMessageDialog(null, "Successfully added Answers.", "Congratulations", JOptionPane.PLAIN_MESSAGE);
        
        mat[Count] = m;
        Count++; 
     
        txtAns1.setText("");
        txtAns2.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed
    //This is the MouseClick-SearchAction 
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String ans1, ans2;
        Maths m;
    
        ans1 = txtAns1.getText();
        ans2 = txtAns2.getText();           
        

            //Finding the match
        for (int i=0; i < Count; i++){   
            m = mat[i];
            if (ans1.equals(m.getAns1()) && ans2.equals(m.getAns2())){
            ans1 = m.getAns1();
            ans2 = m.getAns2();
                   
            
            txtAns1.setText("");
            txtAns2.setText(""); 
            
            }   
            

                
        JOptionPane.showMessageDialog(null, "Answer one " + ans1 + "Answer two :" + ans2,"Attention!", JOptionPane.PLAIN_MESSAGE);            

            txtAns1.setText("");
             txtAns2.setText(""); 
                 return;
                }
             
             
    }//GEN-LAST:event_btnSearchActionPerformed
        //This is the MouseClick-DisplayAction 
    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        String ans1, ans2;
        Maths m;   
        
        if(Count == 0){  
            JOptionPane.showMessageDialog(null, "Ther are no answers saved.", "Attention!", JOptionPane.WARNING_MESSAGE);
             txtAns1.setText("");
             txtAns2.setText("");
        }  
       
        for (int i=0; i < Count; i++){   
            m = mat[i];
            ans1 = m.getAns1();
            ans2 = m.getAns2();
       
            JOptionPane.showMessageDialog(null, "Answer one " + ans1 + "Answer two :" + ans2,"Attention!", JOptionPane.PLAIN_MESSAGE);            
            
            txtAns1.setText("");
             txtAns2.setText("");
        }
        
             txtAns1.setText("");
              txtAns2.setText("");
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SUBJECTS");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void txtAns2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAns2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAns2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblMaths;
    private javax.swing.JLabel lblMathsEquation1;
    private javax.swing.JLabel lblMathsEquation2;
    private javax.swing.JLabel lblMathsQ1;
    private javax.swing.JLabel lblMathsQ1Instruction;
    private javax.swing.JLabel lblMathsQ2;
    private javax.swing.JLabel lblMathsQ2Instruction;
    private javax.swing.JTextField txtAns1;
    private javax.swing.JTextField txtAns2;
    // End of variables declaration//GEN-END:variables
}
