/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 * CourseContentSubjectsPanel.java
 * @author H. Alabi
 * JPANEL for viewing "Subjects" navigation panel
 */
public class CourseContentSubjectsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Screen1Panel
     */
    public CourseContentSubjectsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnMaths = new javax.swing.JButton();
        btnTechnology = new javax.swing.JButton();
        btnScience = new javax.swing.JButton();
        lblSubjects = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(null);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(154, 417, 228, 65);

        btnMaths.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMaths.setText("Maths");
        btnMaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMathsActionPerformed(evt);
            }
        });
        add(btnMaths);
        btnMaths.setBounds(154, 111, 228, 65);

        btnTechnology.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTechnology.setText("Technology");
        btnTechnology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTechnologyActionPerformed(evt);
            }
        });
        add(btnTechnology);
        btnTechnology.setBounds(154, 317, 228, 65);

        btnScience.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnScience.setText("Science");
        btnScience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScienceActionPerformed(evt);
            }
        });
        add(btnScience);
        btnScience.setBounds(154, 217, 228, 65);

        lblSubjects.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSubjects.setForeground(new java.awt.Color(204, 204, 204));
        lblSubjects.setText("Subjects");
        add(lblSubjects);
        lblSubjects.setBounds(213, 29, 103, 29);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(500, 700));
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "COURSE CONTENT");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMathsActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "MATHS");
        }
    }//GEN-LAST:event_btnMathsActionPerformed

    private void btnScienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScienceActionPerformed
        // TODO add your handling code here:
         LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SCIENCE");
        }
    }//GEN-LAST:event_btnScienceActionPerformed

    private void btnTechnologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTechnologyActionPerformed
        // TODO add your handling code here:
         LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "TECHNOLOGY");
        }
    }//GEN-LAST:event_btnTechnologyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMaths;
    private javax.swing.JButton btnScience;
    private javax.swing.JButton btnTechnology;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblSubjects;
    // End of variables declaration//GEN-END:variables
}
