/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 * ExamStudyAidsPanel.java
 * @author P. King
 * JPANEL for viewing details relating to study aids
 */
public class ExamStudyAidsPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudyAids
     */
    public ExamStudyAidsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudyAids = new javax.swing.JLabel();
        lblStudyGuides = new javax.swing.JLabel();
        lblPastPapers = new javax.swing.JLabel();
        scrollStudyGuides = new javax.swing.JScrollPane();
        listStudyGuides = new javax.swing.JList();
        scrollPastPapers = new javax.swing.JScrollPane();
        listPastPapers = new javax.swing.JList();
        scrollTips = new javax.swing.JScrollPane();
        listTips = new javax.swing.JList();
        lblTips = new javax.swing.JLabel();
        scrollRecommendedReading = new javax.swing.JScrollPane();
        listRecommendedReading = new javax.swing.JList();
        scrollFAQ = new javax.swing.JScrollPane();
        listFAQ = new javax.swing.JList();
        lblRecommendedReading = new javax.swing.JLabel();
        lblFAQ = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblStudyAidsIntro = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        lblStudyAids.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblStudyAids.setForeground(new java.awt.Color(255, 255, 255));
        lblStudyAids.setText("Study Aids");
        add(lblStudyAids);
        lblStudyAids.setBounds(180, 20, 160, 40);

        lblStudyGuides.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStudyGuides.setForeground(new java.awt.Color(255, 255, 255));
        lblStudyGuides.setText("Study Guides");
        add(lblStudyGuides);
        lblStudyGuides.setBounds(41, 122, 120, 17);

        lblPastPapers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPastPapers.setForeground(new java.awt.Color(255, 255, 255));
        lblPastPapers.setText("Past Papers");
        add(lblPastPapers);
        lblPastPapers.setBounds(41, 217, 120, 17);

        listStudyGuides.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Mathematics", "Science", "Technology" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollStudyGuides.setViewportView(listStudyGuides);

        add(scrollStudyGuides);
        scrollStudyGuides.setBounds(41, 144, 400, 55);

        listPastPapers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "2012", "2013", "2014", "2015" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollPastPapers.setViewportView(listPastPapers);

        add(scrollPastPapers);
        scrollPastPapers.setBounds(41, 239, 400, 55);

        listTips.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Mathematics", "Science", "Technology" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollTips.setViewportView(listTips);

        add(scrollTips);
        scrollTips.setBounds(41, 334, 400, 55);

        lblTips.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTips.setForeground(new java.awt.Color(255, 255, 255));
        lblTips.setText("Tips");
        add(lblTips);
        lblTips.setBounds(41, 312, 80, 17);

        listRecommendedReading.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "'The Evolution of Physics' by Albert Einstein", "'A Brief History of Time' by Stephen Hawkings", "'Harry Potter and the Philosopher's Stone' by J. K. Rowling" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollRecommendedReading.setViewportView(listRecommendedReading);

        add(scrollRecommendedReading);
        scrollRecommendedReading.setBounds(41, 429, 400, 55);

        listFAQ.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Who", "What", "When", "Where", "How" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollFAQ.setViewportView(listFAQ);

        add(scrollFAQ);
        scrollFAQ.setBounds(41, 524, 400, 55);

        lblRecommendedReading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRecommendedReading.setForeground(new java.awt.Color(255, 255, 255));
        lblRecommendedReading.setText("Recommended Reading");
        add(lblRecommendedReading);
        lblRecommendedReading.setBounds(41, 407, 170, 17);

        lblFAQ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFAQ.setForeground(new java.awt.Color(255, 255, 255));
        lblFAQ.setText("FAQ's");
        add(lblFAQ);
        lblFAQ.setBounds(41, 502, 90, 17);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(140, 610, 214, 30);

        lblStudyAidsIntro.setForeground(new java.awt.Color(255, 255, 255));
        lblStudyAidsIntro.setText("Please click on any of the links to be directed to your area of interest:");
        add(lblStudyAidsIntro);
        lblStudyAidsIntro.setBounds(40, 75, 440, 30);

        lblBackground.setForeground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(500, 700));
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "EXAMS");
        }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblFAQ;
    private javax.swing.JLabel lblPastPapers;
    private javax.swing.JLabel lblRecommendedReading;
    private javax.swing.JLabel lblStudyAids;
    private javax.swing.JLabel lblStudyAidsIntro;
    private javax.swing.JLabel lblStudyGuides;
    private javax.swing.JLabel lblTips;
    private javax.swing.JList listFAQ;
    private javax.swing.JList listPastPapers;
    private javax.swing.JList listRecommendedReading;
    private javax.swing.JList listStudyGuides;
    private javax.swing.JList listTips;
    private javax.swing.JScrollPane scrollFAQ;
    private javax.swing.JScrollPane scrollPastPapers;
    private javax.swing.JScrollPane scrollRecommendedReading;
    private javax.swing.JScrollPane scrollStudyGuides;
    private javax.swing.JScrollPane scrollTips;
    // End of variables declaration//GEN-END:variables
}
