/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package ie.SchoolManagmentSystem.GUI;
import java.awt.CardLayout;
import java.awt.LayoutManager;
import ie.SchoolManagmentSystem.Feedback;
import javax.swing.JOptionPane;

/**
 * ExamResultsPanel.java
 * @author PatrickKing
 * JPANEL for viewing exam results
 */
public class ExamResultsPanel extends javax.swing.JPanel {

    Feedback fb[];
    int Count = 0;
   
    
    /**
     * Creates new form ExamResults
     */
    public ExamResultsPanel() {
        initComponents();
        
        fb = new Feedback[100];
        Count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExamResults = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        comboYear = new javax.swing.JComboBox();
        comboSemester = new javax.swing.JComboBox();
        comboSubject = new javax.swing.JComboBox();
        lblGrade = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();
        btnDisplay = new javax.swing.JButton();
        lblGrade1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnGetGrade = new javax.swing.JButton();
        txtFeedback = new javax.swing.JTextField();
        btnRmove = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        lblExamResults.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblExamResults.setForeground(new java.awt.Color(204, 204, 204));
        lblExamResults.setText("Exam Results");
        add(lblExamResults);
        lblExamResults.setBounds(180, 30, 180, 29);

        lblYear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblYear.setForeground(new java.awt.Color(204, 204, 204));
        lblYear.setText("Year");
        add(lblYear);
        lblYear.setBounds(70, 100, 60, 20);

        lblSemester.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemester.setForeground(new java.awt.Color(204, 204, 204));
        lblSemester.setText("Semester");
        add(lblSemester);
        lblSemester.setBounds(70, 150, 80, 20);

        lblSubject.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(204, 204, 204));
        lblSubject.setText("Subject");
        add(lblSubject);
        lblSubject.setBounds(70, 200, 70, 20);

        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2012-2013", "2013-2014", "2014-2015" }));
        add(comboYear);
        comboYear.setBounds(150, 100, 300, 25);

        comboSemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semester 1", "Semester 2" }));
        add(comboSemester);
        comboSemester.setBounds(150, 150, 300, 25);

        comboSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mathematics", "Science", "Technology" }));
        add(comboSubject);
        comboSubject.setBounds(150, 200, 300, 25);

        lblGrade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGrade.setForeground(new java.awt.Color(204, 204, 204));
        lblGrade.setText("Feedback?");
        add(lblGrade);
        lblGrade.setBounds(210, 340, 90, 17);

        txtGrade.setText("Grade appears here...");
        add(txtGrade);
        txtGrade.setBounds(70, 270, 200, 50);

        btnDisplay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        add(btnDisplay);
        btnDisplay.setBounds(30, 430, 120, 30);

        lblGrade1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGrade1.setForeground(new java.awt.Color(204, 204, 204));
        lblGrade1.setText("Grade");
        add(lblGrade1);
        lblGrade1.setBounds(150, 250, 60, 17);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(200, 490, 120, 30);

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(360, 430, 120, 30);

        btnGetGrade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGetGrade.setText("Get Grade");
        btnGetGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetGradeActionPerformed(evt);
            }
        });
        add(btnGetGrade);
        btnGetGrade.setBounds(320, 280, 120, 30);
        add(txtFeedback);
        txtFeedback.setBounds(80, 370, 360, 28);

        btnRmove.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRmove.setText("Remove");
        btnRmove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmoveActionPerformed(evt);
            }
        });
        add(btnRmove);
        btnRmove.setBounds(200, 430, 120, 30);

        lblBackground.setForeground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(500, 700));
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "EXAMS");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGetGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetGradeActionPerformed
        String year = comboYear.getSelectedItem().toString();
        String semester =comboSemester.getSelectedItem().toString();
        String subject = comboSubject.getSelectedItem().toString();
        
       if(year.equals("2013-2014") && semester.equals("Semester 1"))
       {
           if(subject.equals("Science"))
           {
               txtGrade.setText("40% :)");
           }
           else if(subject.equals("Technology"))
           {
               txtGrade.setText("39% :(");
           }
           else
           {
              txtGrade.setText("100% :D");
           }
       }
        else
       {
           if(subject.equals("Science"))
           {
            txtGrade.setText("25% :,(");
           }
           else if(subject.equals("Technology"))
           {
                txtGrade.setText("96% Well Done");
           }
           else
           {
               txtGrade.setText("0% you suck at maths!!");
           }
       }
        
        JOptionPane.showMessageDialog(null, "Saved", "Attention", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnGetGradeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    String feedback;
    Feedback f;
    feedback = txtFeedback.getText();
    f = new Feedback (feedback);
    JOptionPane.showMessageDialog(null, "feedback added.", "Congratulations", JOptionPane.PLAIN_MESSAGE);
    fb[Count] = f;
    Count++;
    txtFeedback.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
   String feedback;
   Feedback f;
    for (int i=0; i < Count; i++){   
        f = fb[i];
        feedback = f.getFeedback();
        JOptionPane.showMessageDialog(null, "My Feedback: "+feedback, "Student Information", JOptionPane.PLAIN_MESSAGE); 
    }
    txtFeedback.setText("");
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnRmoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmoveActionPerformed
    String feedback;
    Feedback f;
    feedback = txtFeedback.getText();
    for (int i=0; i < Count; i++){ 
        f = fb[i];
        if (feedback.equals(f.getFeedback())){                 
            fb[i] = fb[Count-1];
            fb[Count-1] = null;
            Count--;           
        }  
        JOptionPane.showMessageDialog(null, "Your Feedback has been removed", "Student Information", JOptionPane.PLAIN_MESSAGE); 
    }
    }//GEN-LAST:event_btnRmoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnGetGrade;
    private javax.swing.JButton btnRmove;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox comboSemester;
    private javax.swing.JComboBox comboSubject;
    private javax.swing.JComboBox comboYear;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExamResults;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblGrade1;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtFeedback;
    private javax.swing.JTextField txtGrade;
    // End of variables declaration//GEN-END:variables
}
