/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 * ExamMenuPanel.java
 * @author P. King
 * JPANEL for viewing "Exams" navigation page
 */
public class ExamMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExamMenu
     */
    public ExamMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExams = new javax.swing.JLabel();
        btnExamResults = new javax.swing.JButton();
        btnStudyAids = new javax.swing.JButton();
        btnExamSchedules = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        lblExams.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblExams.setForeground(new java.awt.Color(204, 204, 204));
        lblExams.setText("Exams");
        add(lblExams);
        lblExams.setBounds(200, 30, 160, 50);

        btnExamResults.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExamResults.setText("Exam Results");
        btnExamResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamResultsActionPerformed(evt);
            }
        });
        add(btnExamResults);
        btnExamResults.setBounds(130, 200, 228, 65);

        btnStudyAids.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnStudyAids.setText("Study Aids");
        btnStudyAids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyAidsActionPerformed(evt);
            }
        });
        add(btnStudyAids);
        btnStudyAids.setBounds(130, 310, 228, 65);

        btnExamSchedules.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExamSchedules.setText("Exam Schedules");
        btnExamSchedules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamSchedulesActionPerformed(evt);
            }
        });
        add(btnExamSchedules);
        btnExamSchedules.setBounds(130, 90, 228, 65);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(130, 420, 228, 65);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(500, 700));
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "MAIN");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnExamResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamResultsActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "EXAM RESULTS");
        }
    }//GEN-LAST:event_btnExamResultsActionPerformed

    private void btnExamSchedulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamSchedulesActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "EXAM SCHEDULE");
        }
    }//GEN-LAST:event_btnExamSchedulesActionPerformed

    private void btnStudyAidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyAidsActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "EXAM STUDY AIDS");
        }
    }//GEN-LAST:event_btnStudyAidsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExamResults;
    private javax.swing.JButton btnExamSchedules;
    private javax.swing.JButton btnStudyAids;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExams;
    // End of variables declaration//GEN-END:variables
}
