/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 * SchoolMapBuildingsMainPanel.java
 * @author R. Yson
 * JPANEL for viewing info school grounds
 */
public class SchoolMapBuildingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SchoolMapBuildingsMainPanel
     */
    public SchoolMapBuildingsPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuildingsMain = new javax.swing.JLabel();
        btnBackSchoolMap = new javax.swing.JButton();
        JComboBuildingList = new javax.swing.JComboBox();
        lblBuildingImg = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setLayout(null);

        lblBuildingsMain.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBuildingsMain.setForeground(new java.awt.Color(204, 204, 204));
        lblBuildingsMain.setText("Buildings");
        add(lblBuildingsMain);
        lblBuildingsMain.setBounds(195, 38, 117, 38);

        btnBackSchoolMap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBackSchoolMap.setText("Back");
        btnBackSchoolMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSchoolMapActionPerformed(evt);
            }
        });
        add(btnBackSchoolMap);
        btnBackSchoolMap.setBounds(150, 550, 210, 30);

        JComboBuildingList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "The Great Hall", "Herbology", "Potions", "The Kitchens" }));
        JComboBuildingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBuildingListActionPerformed(evt);
            }
        });
        add(JComboBuildingList);
        JComboBuildingList.setBounds(87, 142, 327, 30);

        lblBuildingImg.setBackground(new java.awt.Color(0, 0, 0));
        lblBuildingImg.setForeground(new java.awt.Color(204, 204, 204));
        lblBuildingImg.setText("<image appears with text when option selected>");
        add(lblBuildingImg);
        lblBuildingImg.setBounds(115, 197, 270, 148);

        lblBackground.setPreferredSize(new java.awt.Dimension(500, 700));
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackSchoolMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSchoolMapActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SCHOOL MAP");
        }
    }//GEN-LAST:event_btnBackSchoolMapActionPerformed

    private void JComboBuildingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBuildingListActionPerformed
        
    }//GEN-LAST:event_JComboBuildingListActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JComboBuildingList;
    private javax.swing.JButton btnBackSchoolMap;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBuildingImg;
    private javax.swing.JLabel lblBuildingsMain;
    // End of variables declaration//GEN-END:variables
}

/*ERROR BANK
* 1.) Did not double-click on JButtons in Design mode - need Netbeans to 
* automatically generate ActionEvent codes or it won't understand perfectly
* fine hard-coded ActionEvents!!!
*/