/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import javax.swing.JPanel;

/**
 * SchoolSystemApp.java
 * @author H. Alabi, P. King, D. Whelan, R. Yson
 * JFrame for app
 */
public class SchoolSystemApp extends javax.swing.JFrame {
    JPanel cardsContainer;
    /**
     * Creates new form MainJFrameApp
     */
    public SchoolSystemApp() {
        initComponents();
        
        // DON'S CARDS
        MainScreenPanel mainCard = new MainScreenPanel();
        StudentsPanel screen1Card = new StudentsPanel();
        AdministrationPanel screen2Card = new AdministrationPanel();
        AdministrationPanelUploads screen3Card = new AdministrationPanelUploads();
        AdministrationPanelGrades screen4Card = new AdministrationPanelGrades();
        AdministrationPanelAttendance screen5Card = new AdministrationPanelAttendance();
        AdministrationPanelEditStudents screen25Card = new AdministrationPanelEditStudents();
        
        // REY'S CARDS
        CommunicationsPanel screen6Card = new CommunicationsPanel();
        ImportantNewsPanel screen7Card = new ImportantNewsPanel();
        ContactListPanel screen8Card = new ContactListPanel();
        AddContactPanel screen9Card = new AddContactPanel();
        CalendarPanel screen10Card = new CalendarPanel();
        SchoolMapPanel screen11Card = new SchoolMapPanel();
        SchoolMapBuildingsPanel screen12Card = new SchoolMapBuildingsPanel();
        SchoolMapDirectionsPanel screen13Card = new SchoolMapDirectionsPanel();
        
        // ENGLISH PATRICK'S CARDS
        ExamMenuPanel screen14Card = new ExamMenuPanel();
        ExamResultsPanel screen15Card = new ExamResultsPanel();
        ExamSchedulePanel screen16Card = new ExamSchedulePanel();
        ExamStudyAidsPanel screen17Card = new ExamStudyAidsPanel();
        
        // HABEEB'S CARDS
        CourseContentMenuPanel screen18Card = new CourseContentMenuPanel();
        CourseContentSubjectsPanel screen19Card = new CourseContentSubjectsPanel();
        CourseContentMathsPanel screen20Card = new CourseContentMathsPanel();
        CourseContentSciencePanel screen21Card = new CourseContentSciencePanel();
        CourseContentTechnologyPanel screen22Card = new CourseContentTechnologyPanel();
        CourseContentCAPanel screen23Card = new CourseContentCAPanel();
        CourseContentNotesPanel screen24Card = new CourseContentNotesPanel();
        
        // CONFIGURATION OF JPANELS
        cardsContainer = new JPanel(new CardLayout());
        
        // DON'S CARDSCONTAINERS
        cardsContainer.add(mainCard, "MAIN");
        cardsContainer.add(screen1Card,"STUDENT");
        cardsContainer.add(screen2Card, "ADMIN");
        cardsContainer.add(screen3Card, "UPLOADS");
        cardsContainer.add(screen4Card, "GRADES");
        cardsContainer.add(screen5Card, "ATTENDANCE");
        cardsContainer.add(screen25Card, "ADDREMOVE");
        
        
        // REY'S CARDSCONTAINERS
        cardsContainer.add(screen6Card, "COMMUNICATIONS");
        cardsContainer.add(screen7Card,"NEWS");
        cardsContainer.add(screen8Card,"CONTACT LIST");
        cardsContainer.add(screen9Card,"ADD CONTACT");
        cardsContainer.add(screen10Card,"CALENDAR");
        cardsContainer.add(screen11Card,"SCHOOL MAP");
        cardsContainer.add(screen12Card,"BUILDINGS");
        cardsContainer.add(screen13Card,"DIRECTIONS");
        
        // ENGLISH PATRICK'S CARDSCONTAINERS
        cardsContainer.add(screen14Card, "EXAMS");
        cardsContainer.add(screen15Card, "EXAM RESULTS");
        cardsContainer.add(screen16Card, "EXAM SCHEDULE");
        cardsContainer.add(screen17Card, "EXAM STUDY AIDS");
        
        // HABEEB'S CARDSCONTAINERS
        cardsContainer.add(screen18Card, "COURSE CONTENT");
        cardsContainer.add(screen19Card, "SUBJECTS");
        cardsContainer.add(screen20Card, "MATHS");
        cardsContainer.add(screen21Card, "SCIENCE");
        cardsContainer.add(screen22Card, "TECHNOLOGY");
        cardsContainer.add(screen23Card, "CA");
        cardsContainer.add(screen24Card, "NOTES");
        
        // ADD CARDSCONTAINERS TO JFRAME
        this.setLayout(new FlowLayout());
        this.add(cardsContainer);
        CardLayout cl = (CardLayout)(cardsContainer.getLayout());
        cl.show(cardsContainer, "MAIN");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(516, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolSystemApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolSystemApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
