/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java. awt.LayoutManager;
import javax.swing.JOptionPane;

/**
 * SchoolMapJourneyPanel.java
 * @author R. Yson
 * JPANEL for obtaining directions to different areas of school
 */
public class SchoolMapDirectionsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SchoolMapDirectionsMainPanel
     */
    public SchoolMapDirectionsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpTransportMode = new javax.swing.ButtonGroup();
        lblDirectionsMain = new javax.swing.JLabel();
        btnBackSchoolMap = new javax.swing.JButton();
        lblStartLocation = new javax.swing.JLabel();
        lblEndLocation = new javax.swing.JLabel();
        lblDepartureTime = new javax.swing.JLabel();
        lblTransportMode = new javax.swing.JLabel();
        rBtnWalking = new javax.swing.JRadioButton();
        rBtnCar = new javax.swing.JRadioButton();
        rBtnBike = new javax.swing.JRadioButton();
        txtStartLocation = new javax.swing.JTextField();
        txtDepartureTime = new javax.swing.JTextField();
        txtEndLocation = new javax.swing.JTextField();
        lblJourneyDetails = new javax.swing.JLabel();
        scrollDirections = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblJourneyDuration = new javax.swing.JLabel();
        txtJourneyDuration = new javax.swing.JTextField();
        rBtnBus = new javax.swing.JRadioButton();
        rBtnTrain = new javax.swing.JRadioButton();
        lblDistance = new javax.swing.JLabel();
        txtDistance = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 700));
        setLayout(null);

        lblDirectionsMain.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDirectionsMain.setForeground(new java.awt.Color(204, 204, 204));
        lblDirectionsMain.setText("Journey Guide");
        add(lblDirectionsMain);
        lblDirectionsMain.setBounds(175, 29, 200, 29);

        btnBackSchoolMap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBackSchoolMap.setText("Back");
        btnBackSchoolMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSchoolMapActionPerformed(evt);
            }
        });
        add(btnBackSchoolMap);
        btnBackSchoolMap.setBounds(236, 547, 214, 30);

        lblStartLocation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStartLocation.setForeground(new java.awt.Color(204, 204, 204));
        lblStartLocation.setText("Start Location:");
        add(lblStartLocation);
        lblStartLocation.setBounds(72, 76, 112, 17);

        lblEndLocation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEndLocation.setForeground(new java.awt.Color(204, 204, 204));
        lblEndLocation.setText("End Location:");
        add(lblEndLocation);
        lblEndLocation.setBounds(72, 228, 95, 17);

        lblDepartureTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDepartureTime.setForeground(new java.awt.Color(204, 204, 204));
        lblDepartureTime.setText("Departure Time:");
        add(lblDepartureTime);
        lblDepartureTime.setBounds(72, 114, 112, 17);

        lblTransportMode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTransportMode.setForeground(new java.awt.Color(204, 204, 204));
        lblTransportMode.setText("Mode of Transport:");
        add(lblTransportMode);
        lblTransportMode.setBounds(72, 152, 134, 17);

        btnGrpTransportMode.add(rBtnWalking);
        rBtnWalking.setForeground(new java.awt.Color(204, 204, 204));
        rBtnWalking.setSelected(true);
        rBtnWalking.setText("Walk");
        add(rBtnWalking);
        rBtnWalking.setBounds(72, 187, 49, 23);

        btnGrpTransportMode.add(rBtnCar);
        rBtnCar.setForeground(new java.awt.Color(204, 204, 204));
        rBtnCar.setText("Car");
        add(rBtnCar);
        rBtnCar.setBounds(237, 187, 50, 23);

        btnGrpTransportMode.add(rBtnBike);
        rBtnBike.setForeground(new java.awt.Color(204, 204, 204));
        rBtnBike.setText("Bike");
        add(rBtnBike);
        rBtnBike.setBounds(390, 187, 60, 23);
        add(txtStartLocation);
        txtStartLocation.setBounds(236, 76, 214, 20);
        add(txtDepartureTime);
        txtDepartureTime.setBounds(236, 114, 214, 20);
        add(txtEndLocation);
        txtEndLocation.setBounds(236, 228, 214, 20);

        lblJourneyDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJourneyDetails.setForeground(new java.awt.Color(204, 204, 204));
        lblJourneyDetails.setText("Journey Details:");
        add(lblJourneyDetails);
        lblJourneyDetails.setBounds(72, 405, 110, 17);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Directions appear here\nafter clicking \"Submit\"...");
        scrollDirections.setViewportView(jTextArea1);

        add(scrollDirections);
        scrollDirections.setBounds(236, 405, 214, 86);

        lblJourneyDuration.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblJourneyDuration.setForeground(new java.awt.Color(204, 204, 204));
        lblJourneyDuration.setText("Journey Duration:");
        add(lblJourneyDuration);
        lblJourneyDuration.setBounds(72, 509, 125, 17);
        add(txtJourneyDuration);
        txtJourneyDuration.setBounds(236, 509, 214, 20);

        btnGrpTransportMode.add(rBtnBus);
        rBtnBus.setForeground(new java.awt.Color(204, 204, 204));
        rBtnBus.setText("Bus");
        add(rBtnBus);
        rBtnBus.setBounds(155, 187, 50, 23);

        btnGrpTransportMode.add(rBtnTrain);
        rBtnTrain.setForeground(new java.awt.Color(204, 204, 204));
        rBtnTrain.setText("Train");
        add(rBtnTrain);
        rBtnTrain.setBounds(318, 187, 50, 23);

        lblDistance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDistance.setForeground(new java.awt.Color(204, 204, 204));
        lblDistance.setText("Distance to Travel:");
        add(lblDistance);
        lblDistance.setBounds(72, 266, 128, 17);
        add(txtDistance);
        txtDistance.setBounds(236, 263, 214, 20);

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(236, 301, 214, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackSchoolMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSchoolMapActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SCHOOL MAP");
        }
    }//GEN-LAST:event_btnBackSchoolMapActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        JOptionPane.showMessageDialog(null, "Details submitted!", "Attention", JOptionPane.WARNING_MESSAGE);  
    }//GEN-LAST:event_btnSubmitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackSchoolMap;
    private javax.swing.ButtonGroup btnGrpTransportMode;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDepartureTime;
    private javax.swing.JLabel lblDirectionsMain;
    private javax.swing.JLabel lblDistance;
    private javax.swing.JLabel lblEndLocation;
    private javax.swing.JLabel lblJourneyDetails;
    private javax.swing.JLabel lblJourneyDuration;
    private javax.swing.JLabel lblStartLocation;
    private javax.swing.JLabel lblTransportMode;
    private javax.swing.JRadioButton rBtnBike;
    private javax.swing.JRadioButton rBtnBus;
    private javax.swing.JRadioButton rBtnCar;
    private javax.swing.JRadioButton rBtnTrain;
    private javax.swing.JRadioButton rBtnWalking;
    private javax.swing.JScrollPane scrollDirections;
    private javax.swing.JTextField txtDepartureTime;
    private javax.swing.JTextField txtDistance;
    private javax.swing.JTextField txtEndLocation;
    private javax.swing.JTextField txtJourneyDuration;
    private javax.swing.JTextField txtStartLocation;
    // End of variables declaration//GEN-END:variables
}

/*ERROR BANK
* 1.) Did not double-click on JButtons in Design mode - need Netbeans to 
* automatically generate ActionEvent codes or it won't understand perfectly
* fine hard-coded ActionEvents!!!
*/