/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.SchoolManagmentSystem.GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 * StudentsPanel.java
 * @author Whelan & Yson
 * JPANEL for viewing "Students" navigation page
 */
public class StudentsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Screen1Panel
     */
    public StudentsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudents = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCalendar = new javax.swing.JButton();
        btnCommunications = new javax.swing.JButton();
        btnSchoolMap = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setLayout(null);

        lblStudents.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblStudents.setForeground(new java.awt.Color(204, 204, 204));
        lblStudents.setText("Students");
        add(lblStudents);
        lblStudents.setBounds(206, 29, 106, 29);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(150, 420, 228, 65);

        btnCalendar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalendar.setText("Calendar");
        btnCalendar.setPreferredSize(new java.awt.Dimension(145, 25));
        btnCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarActionPerformed(evt);
            }
        });
        add(btnCalendar);
        btnCalendar.setBounds(154, 114, 228, 65);

        btnCommunications.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCommunications.setText("Communications");
        btnCommunications.setPreferredSize(new java.awt.Dimension(145, 25));
        btnCommunications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunicationsActionPerformed(evt);
            }
        });
        add(btnCommunications);
        btnCommunications.setBounds(154, 216, 228, 65);

        btnSchoolMap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSchoolMap.setText("School Map");
        btnSchoolMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSchoolMapActionPerformed(evt);
            }
        });
        add(btnSchoolMap);
        btnSchoolMap.setBounds(154, 315, 228, 65);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/SchoolManagmentSystem/GUI/ExamsAppBackground.png"))); // NOI18N
        lblBackground.setPreferredSize(new java.awt.Dimension(500, 700));
        add(lblBackground);
        lblBackground.setBounds(0, 0, 500, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "MAIN");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCommunicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunicationsActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "COMMUNICATIONS");
        }
    }//GEN-LAST:event_btnCommunicationsActionPerformed

    private void btnSchoolMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSchoolMapActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SCHOOL MAP");
        }
    }//GEN-LAST:event_btnSchoolMapActionPerformed

    private void btnCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "CALENDAR");
        }
    }//GEN-LAST:event_btnCalendarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalendar;
    private javax.swing.JButton btnCommunications;
    private javax.swing.JButton btnSchoolMap;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblStudents;
    // End of variables declaration//GEN-END:variables
}
